# deployment:
#   imageVersion: IMAGE_VERSION # we can repace during run time based on the ci job version
#   imageUrl: lakshmi1092/catalogue
# hpa:
#   maxreplicas: 10
#   utilisation: 75

deployment:
  imageVersion: IMAGE_VERSION
  imageUrl: 143094436925.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue

hpa:
  maxreplicas: 10
  utilisation: 75